include:
  # - board: corneish_zen_v1_left
  #   # snippet: zmk-usb-logging  # uncomment to enable logging
  - board: corneish_zen_v1_right
  - board: corneish_zen_v1_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corneish_zen_v1_left_with_studio
